// Generated by IB v0.8.0 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <CoreLocation/CoreLocation.h>
#import <CFNetwork/CFNetwork.h>
#import <MobileCoreServices/MobileCoreServices.h>
#import <QuartzCore/QuartzCore.h>
#import <Security/Security.h>
#import <SystemConfiguration/SystemConfiguration.h>
#import <CoreLocation/CoreLocation.h>
#import <Photos/Photos.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
@end

@interface CheckinVenueCell: UITableViewCell

@property IBOutlet id name_label;
@property IBOutlet id address_label;

@end

@interface CheckinController: UITableViewController
-(IBAction) viewDidLoad;
-(IBAction) update_view;
-(IBAction) close_view;
-(IBAction) venues;
-(IBAction) foursquare;
-(IBAction) manager;

@end

@interface CheckinPostController: UIViewController

@property IBOutlet id text_view;
@property IBOutlet id image_view;

-(IBAction) viewDidLoad;
-(IBAction) publish:(id) sender;
-(IBAction) pick_photo:(id) sender;
-(IBAction) image;
-(IBAction) firebase;

@end

@interface MainController: UIViewController

@property IBOutlet id location_button;
@property IBOutlet id swarm_checkin_button;
@property IBOutlet id login;
@property IBOutlet id connect_foursquare;
@property IBOutlet id connect_twitter;

-(IBAction) hello;
-(IBAction) viewDidLoad;
-(IBAction) authorize_location:(id) sender;
-(IBAction) swarm_checkin:(id) sender;
-(IBAction) open_checkin_screen;
-(IBAction) open_login_screen;
-(IBAction) open_connect_foursquare;
-(IBAction) open_connect_twitter;
-(IBAction) firebase;
-(IBAction) manager;

@end

@interface Foursquare: NSObject
-(IBAction) initialize:(id) params;
-(IBAction) qs_prefix;

@end

@interface UIImage: NSObject
-(IBAction) normalize;

@end

