// Generated by IB v0.8.0 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation AppDelegate
@end

@implementation CheckinVenueCell
@end

@implementation CheckinController
@end

@implementation CheckinPostController
@end

@implementation LoginController
@end

@implementation MainController
@end

@implementation TravelNewController
@end

@implementation Foursquare
@end

@implementation UIImage
@end

